sudo: required
services:
  - docker

before_install:
  - docker build -t nomanaadma/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nomanaadma/docker-react npm run test

before_deploy:
  - rvm 1.9.3 do gem install aws-sdk -v 2.1.36

deploy:
  provider: elasticbeakstalk
  region: "us-east-2"
  app: "docker-react"
  evn: "Docker-React-Env"
  bucket_name: elasticbeanstalk-us-east-2-581542056104
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY